---
version: "2.1"
services:
  flaresolverr:
    image: drlocke/flaresolverr:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/London
      - HOST=0.0.0.0
    ports:
      - "8192:8191"
    depends_on:
      - nginx
    restart: unless-stopped
  nginx:
    image: nginx:alpine
    ports:
      - "8191:8191"
    volumes:
      - ./resources/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./resources/nginx/.htpasswd:/etc/nginx/.htpasswd:ro
    restart: unless-stopped

