---
version: "2.1"
services:
  flaresolverr:
    image: drlocke/flaresolverr:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/London
      - HOST=127.0.0.1
      - USER=${USER}
      - PW=${PW}
    ports:
      - "8191:8191"
    restart: unless-stopped

